# config/module.yml  ← full content
name: config

build:
  cmake: .
  kconfig: totem.conf   # (your existing Kconfig fragment)

boards:
  - boards              # <─ tells Zephyr “add boards/ to BOARD_ROOT”
