name: Build CodMiryoku Firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install west and dependencies
        run: |
          pip install west
          sudo apt update
          sudo apt install -y ninja-build gperf ccache dfu-util device-tree-compiler wget \
                              python3-pip python3-setuptools python3-wheel xz-utils file \
                              make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
          west init
          west update
          west zephyr-export
          pip install -r zmk/app/zephyr/scripts/requirements.txt

      - name: Build Totem Left
        run: |
          west build -s zmk/app -d build/left \
            -b seeeduino_xiao_ble \
            -- -DSHIELD=totem_left -DZMK_CONFIG=./config

      - name: Build Totem Right
        run: |
          west build -s zmk/app -d build/right \
            -b seeeduino_xiao_ble \
            -- -DSHIELD=totem_right -DZMK_CONFIG=./config

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/left/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2
