name: "Build Totem Firmware"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [seeeduino_xiao_ble]
        shield: [totem_left, totem_right]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install west and dependencies
        run: |
          pip install west
          west init -l zmk
          west update
          west zephyr-export
          pip install -r zmk/zephyr/scripts/requirements.txt

      - name: Build ${{ matrix.shield }}
        run: |
          west build -s zmk/app -b ${{ matrix.board }} \
            -d build/${{ matrix.shield }} \
            -- -DSHIELD=${{ matrix.shield }} \
               -DZMK_CONFIG=codmiryoku/config
